<?php
/**
 * @file
 * Code for the Kendra Social Services feature.
 */

include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'kendra_social_services') . '/kendra_social_services.features.inc';
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'kendra_social_services') . '/kendra_social_services.resources.inc';
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'kendra_social_services') . '/kendra_social_services.callbacks.inc';

function kendra_social_services_permission() {
	return array(
    'access kendra social connect' => array(
      'title' => t('Access Kendra Social Connect services'), 
      'description' => t('Perform social connect operations via the API'),
	),
	);
}

/**
 * Implementation of hook_services_resources().
 */
function kendra_social_services_services_resources() {
	$resources = kendra_social_services_services_get_mappings();
	return $resources;
}
