<?php

/**
 * @file
 * Kendra Social Tests module file.
 */

/**
 * @defgroup kendra_social_test
 * @ingroup kendra_social_test
 * @{
 * These functions exercise the Kendra Social API features using AJAX.
 */

/**
 * Implements hook_init().
 function kendra_social_test_init() {
 drupal_get_path('module', 'kendra_social_test') . '/kendra_social_test.css';
 drupal_get_path('module', 'kendra_social_test') . '/kendra_social_test.js';
 }
 */

/**
 * Implements hook_menu().
 *
 * Sets up calls to drupal_get_form() for all our example cases.
 */
function kendra_social_test_menu() {
	$items = array();

	// Generate different textfields based on form state.
	$items['kendra_social_test/kendra_social_test'] = array(
    'title' => 'Kendra Social API Test',
	    'page callback' => 'drupal_get_form',
    'page arguments' => array('kendra_social_test_api'),
    'access callback' => TRUE,
    'expanded' => TRUE,
      'weight' => 0,
	);

	return $items;
}

/**
 * Exercise the Kendra Social API features
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function kendra_social_test_api($form, &$form_state) {
	$form['#attached']['css'] = array(
	drupal_get_path('module', 'kendra_social_test') . '/kendra_social_test.css',
	);
	$form['#attached']['js'] = array(
	drupal_get_path('module', 'kendra_social_test') . '/kendra_social_test.js',
	);

	$kendra_social_test_extended_params = FALSE;

	$form['kendra-social-box'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="kendra-social-box">',
    '#suffix' => '</div>',
    '#markup' => '<h1>What is your Request?</h1>',
	);

	global $user;
	$uid = $user->uid;

	$form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Endpoint URL'),
    '#prefix' => '<div id="replace_textfield_div">',
    '#suffix' => '</div>',
    '#required' => TRUE,
    '#default_value' => "/saracen/0.1/user/" . $uid,
    '#size' => 32,
    '#maxlength' => 32,
	);

	$options_content_type = _kendra_social_test_get_content_type_options();
	$selected_content_type = isset($form_state['values']['content_type']) ? $form_state['values']['content_type'] : key($options_content_type);

	$options_method = _kendra_social_test_get_method_options();
	$selected_method = isset($form_state['values']['method']) ? $form_state['values']['method'] : key($options_method);

	$options_url = isset($form_state['values']['url']) ? $form_state['values']['url'] : '';

	$form['content_type'] = array(
    '#type' => 'select',
    '#title' => 'Content Type',
    '#options' => $options_content_type,
    '#default_value' => $selected_content_type,
    '#required' => TRUE,
	);

	$form['method'] = array(
    '#type' => 'select',
    '#title' => 'HTTP Method',
    '#options' => $options_method,
    '#default_value' => $selected_method,
    '#required' => TRUE,
	);

	if ($kendra_social_test_extended_params) {
		// Because we have many fields with the same values, we have to set
		// #tree to be able to access them.
		$form['#tree'] = TRUE;
		$form['params_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Parameters'),
		// Set up the wrapper so that AJAX will be able to replace the fieldset.
    '#prefix' => '<div id="params-fieldset-wrapper">',
    '#suffix' => '</div>',
		);

		$form['params_fieldset']['add_param'] = array(
    '#type' => 'submit',
    '#value' => t('Add a parameter'),
    '#submit' => array('kendra_social_test_add_more_add_one'),
		// See the kendra_social_test in kendra_social_test.module for more details on the
		// properties of #ajax.
    '#ajax' => array(
      'callback' => 'kendra_social_test_add_more_callback',
      'wrapper' => 'params-fieldset-wrapper',
		),
		);

		// Build the fieldset with the proper number of params. We'll use
		// $form_state['num_params'] to determine the number of textfields to build.
		if (empty($form_state['num_params'])) {
			$form_state['num_params'] = 1;
		}
		for ($i = 0; $i < $form_state['num_params']; $i++) {
			$form['params_fieldset']['param'][$i] = array(
      '#type' => 'textfield',
      '#title' => t('Parameter'),
			);
		}
		if ($form_state['num_params'] > 1) {
			$form['params_fieldset']['remove_param'] = array(
      '#type' => 'submit',
      '#value' => t('Remove last parameter'),
      '#submit' => array('kendra_social_test_add_more_remove_one'),
      '#ajax' => array(
        'callback' => 'kendra_social_test_add_more_callback',
        'wrapper' => 'params-fieldset-wrapper',
			),
			);
		}
	} else {

		$form['data'] = array(
	 '#type' => 'textarea',
	 '#title' => 'Data',
	 '#default_value' => '',
	 '#required' => FALSE,
	 );
	}

	$form['submit'] = array(
    '#type' => 'submit',
    '#ajax' => array(
	//'callback' => 'kendra_social_test_submit_driven_callback',
	'keypress' => TRUE,
	//'path' => $options_url,
	'wrapper' => 'response',
      'name' => 'submit1',
	),
    '#value' => t('Submit'),
	);

	$form['textfields'] = array(
    '#title' => t("Server response"),
    '#prefix' => '<div id="response-fields">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
	);

	$form['textfields']['response'] = array(
    '#type' => 'markup',
	'#title' => t("Response"),
    '#prefix' => '<div id="response">',
    '#suffix' => '</div>',
    '#markup' => '',
	);

	return $form;
}

/**
 * Callback for both ajax-enabled buttons.
 *
 * Selects and returns the fieldset with the params in it.
 */
function kendra_social_test_add_more_callback($form, $form_state) {
	return $form['params_fieldset'];
}

/**
 * Submit handler for the "add-one-more" button.
 *
 * Increments the max counter and causes a rebuild.
 */
function kendra_social_test_add_more_add_one($form, &$form_state) {
	$form_state['num_params']++;
	$form_state['rebuild'] = TRUE;
}

/**
 * Submit handler for the "remove one" button.
 *
 * Decrements the max counter and causes a form rebuild.
 */
function kendra_social_test_add_more_remove_one($form, &$form_state) {
	if ($form_state['num_params'] > 1) {
		$form_state['num_params']--;
	}
	$form_state['rebuild'] = TRUE;
}

/**
 */
function kendra_social_test_validate(&$form_state, $form) {
	if (empty($form_state['values']['url']['#value'])) {
		form_set($form_state['values']['url'], t('This field is required.'));
		return false;
	} else if (!valid_url($form_state['values']['url'])) {
		form_set_error('url', t('Enter a valid URL.'));
		return false;
	}
	return true;
}

/**
 * Helper function to populate a dropdown.
 *
 * @return array of options
 */
function _kendra_social_test_get_content_type_options() {
	// drupal_map_assoc() just makes an array('String' => 'String'...).
	return drupal_map_assoc(array('application/x-www-form-urlencoded', 'application/json', 'application/atom+xml'));
}

/**
 * Helper function to populate a dropdown.
 *
 * @return array of options
 */
function _kendra_social_test_get_method_options() {
	// drupal_map_assoc() just makes an array('String' => 'String'...).
	return drupal_map_assoc(array('GET', 'POST', 'PUT', 'DELETE', 'HEAD', 'OPTIONS', 'PROPFIND', 'COPY', 'MOVE'));
}

/**
 * Select the 'response' element, change the markup in it, and return it as a
 * renderable array.
 *
 * @return renderable array (the response element)
 */
function kendra_social_test_submit_driven_callback($form, $form_state) {
	if (kendra_social_test_validate($form_state, $form)) {
		$element = $form['response'];
		$element['#markup'] = "Clicked submit ({$form_state['values']['op']}): " . date('c');
		return $element;
	}
}

/**
 * @} End of "defgroup kendra_social_test".
 */
