<?php

variable_set('KENDRA_SOCIAL_SERVICES_ENDPOINT_NAME', 'saracen');
variable_set('KENDRA_SOCIAL_SERVICES_ENDPOINT_PREFIX', 'saracen/0.1');

include_once('kendra_social_config.features.inc');

/**
 * Implementation of hook_menu().
 */
function kendra_social_config_menu() {
  $items = array();
  $items['home'] = array(
    'page callback' => 'kendra_social_front_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Front page callback.
 */
function kendra_social_front_page() {
  $context = context_load('front_page');
  context_set('context', 'front_page', $context);
  return '';
}
