<?php
// NB::: Need to replace with refactored version...
function _kendra_social_media_getitem($id) {
  $result = db_query("SELECT nid FROM {node} WHERE title=:title LIMIT 1", array(':title' => $id));
  foreach ($result as $node) {
    $node = node_load($node->nid);
    $node->predicates = unserialize($node->field_media_tmp['und'][0]['value']);
    unset($node->field_media_tmp);
    return $node;
  }
  return $node;
  /*
  $data = cache_get('temp_kendra_store_' . $id);
  if (!isset($data->data)) {
    return "Item not found";
  }
  return $data->data;
*/
}

function _kendra_social_media_register($identifier = NULL, $userid = NULL, $album_id = NULL, $data = NULL) {
  //	return "registered content";
  //	return func_get_args();
  $result = db_query("SELECT nid FROM {node} WHERE title=:title LIMIT 1", array(':title' => $data['identifier']));
  $nid = NULL;
  foreach ($result as $record) {
    if (isset($record->nid)) {
      $nid = $record->nid;
    }
  }
  if (isset($nid)) {
    $node = node_load($nid);
  }
  else {
    $node         = new StdClass();
    $node->type   = 'kendra_mediaitem';
    $node->status = 1;
    $node->title  = $data['identifier'];
    $node->uid    = 1;
    if (isset($userid)) {
      $node->uid = $userid;
    }
    $node->language = 'und';
  }
  $node->field_media_id['und'][0]['value'] = $data['identifier'];
  $node->field_media_tmp['und'][0]['value'] = serialize($data);
  node_object_prepare($node);
  node_save($node);
  cache_set('temp_kendra_store_' . $data['identifier'], $data);
  return "registered: " . $data['identifier'];
}

function _kendra_social_media_search_content($query, $type, $filter, $sort) {
  return "search result";
}

function _kendra_media_temp_callback() {
  return TRUE;
}

//function kendra_social_media_services_resources() {}